Smile_Plaza/main/posts/forms.py
from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import (StringField, SubmitField, TextAreaField)
from wtforms.validators import DataRequired
from main.models import User
class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

Smile_Plaza/main/main1/routes.py
from flask import render_template, request, Blueprint, abort
from flask_login import current_user, login_required
from main.models import Post

main1 = Blueprint('main', __name__)

@main1.route("/")
@main1.route("/home")
def home():
    return render_template('home.html')

@main1.route("/admin_announcement")
@login_required
def admin_announcement():
    if current_user.id == 1:
        page = request.args.get('page', 1, type=int)
        posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
        #SELECT * FROM Post ORDER BY date_posted DESC LIMIT 5 OFFSET (page - 1) * 5;
        return render_template('admin_announcement.html', title='Announcement', posts=posts)
    else:
        return render_template('errors/403.html', title='Error 403')

@main1.route("/customer_announcement")
@login_required
def customer_announcement():
    if current_user.id != 1:
        page = request.args.get('page', 1, type=int)
        posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
        #SELECT * FROM Post ORDER BY date_posted DESC LIMIT 5 OFFSET (page - 1) * 5;
        return render_template('customer_announcement.html', title='Announcement', posts=posts)
    else:
        return render_template('admin_announcement.html', title='Announcement', posts=posts)
    
@main1.route("/appointment")
@login_required
def appointment():  
    if current_user.id != 1:
        return render_template('appointment.html', title='Appointment')
    else:
        return render_template('errors/403.html')

@main1.route("/history")
@login_required
def history():
    if current_user.id == 1:
        return render_template('errors/403.html')
    else:
        return render_template('history.html', title='History')

Smile_Plaza/main/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from main import db
from main.models import Post
from main.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route("/new_post", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if current_user.id == 1:
        if form.validate_on_submit():
            post = Post(title=form.title.data, content=form.content.data, author=current_user)
            db.session.add(post)
            #INSERT INTO Post (title, content, author) VALUES ('{form.title.data}', '{form.content.data}', '{current_user}');
            db.session.commit()
            flash('Your post has been created!', 'success')
            return redirect(url_for('posts.new_post'))
    else:
        return render_template('errors/403.html', title='Error 403')
    return render_template('new_post.html', title='New Post', form=form, legend='New Post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    if current_user.id != 1: 
        abort(403)
    post = Post.query.get_or_404(post_id) #SELECT * FROM Post WHERE id = {post_id};
    return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id) #SELECT * FROM Post WHERE id = {post_id};
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        #UPDATE Post SET title = '{form.title.data}', content = '{form.content.data}' WHERE id = {post_id};
        db.session.commit() 
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('new_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id) #SELECT * FROM Post WHERE id = {post_id};
    if post.author != current_user:
        abort(403)
    else:
        db.session.delete(post) #DELETE FROM Post WHERE id = {post_id};
        db.session.commit()
        flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.admin_announcement'))

Smile_Plaza/main/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from main import db, bcrypt, mail
from main.models import User, Post
from main.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, ContactForm,
                                   ResetPasswordRequestForm, ResetPasswordForm)
from main.users.utils import save_picture, send_password_reset_email
from flask_mail import Message

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:  
        return redirect(url_for('users.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(FName=form.FName.data, 
                    MidName=form.MidName.data, 
                    LName=form.LName.data, 
                    gender=form.gender.data,
                    birthday=form.birthday.data, 
                    age=form.age.data, 
                    contact=form.contact.data,
                    address=form.address.data,
                    username=form.username.data, 
                    email=form.email.data, 
                    password=hashed_password)
        db.session.add(user) 
        '''
        INSERT INTO User (FName, MidName, LName, gender, birthday, age, contact, address, username, email, password)
        VALUES ('{form.FName.data}', '{form.MidName.data}', '{form.LName.data}', '{form.gender.data}', '{form.birthday.data}', 
        '{form.age.data}', '{form.contact.data}', '{form.address.data}', '{form.username.data}', '{form.email.data}', '{hashed_password}')
        '''
        db.session.commit() 
        #COMMIT
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        if current_user.id == 1:
            return redirect(url_for('users.admin_dashboard')) 
        else:
            return redirect(url_for('main.customer_announcement'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first() #SELECT * FROM User WHERE email = '{form.email.data}' LIMIT 1;
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            if current_user.id == 1: 
                return render_template('admin_dashboard.html', title='Admin Page') 
            else:
                return redirect(url_for('main.customer_announcement'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm() 
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file #UPDATE User SET image_file = '{picture_file}' WHERE id = {current_user.id};
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.contact = form.contact.data
        '''
        UPDATE User 
        SET current_user.username = '{form.username.data}', current_user.email = '{form.email.data}', current_user.contact = '{form.contact.data}'
        WHERE id = {current_user.id};
        '''
        db.session.commit() 
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.contact.data = current_user.contact
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('users.login'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        '''
        UPDATE User SET password = '{hashed_password}' WHERE id = {user.id};
        '''
        flash('Your password has been reset.')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', form=form)

@users.route('/reset_password_request', methods=['GET', 'POST'])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first() #SELECT * FROM User WHERE email = '{form.email.data}' LIMIT 1;
        if user:
            send_password_reset_email(user)
            flash('Check your email for the instructions to reset your password')
            return redirect(url_for('users.login'))
        else:
             flash('No email found.')
             return redirect(url_for('users.reset_password_request'))
    return render_template('reset_password_request.html',
                           title='Reset Password', form=form)

@users.route("/contact", methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        msg = Message(subject=form.subject.data,
                      sender=('{} <{}>'.format(form.name.data, form.email.data)),
                      recipients= ['brionessean500@gmail.com'],
                      body='{}'.format(form.message.data) + ' \n Email: {} \n Contact Number: {}'.format(form.email.data, form.contact_number.data))
        mail.send(msg)
        return redirect(url_for('users.contact'))
    return render_template('contact.html', title='Contact Us', form=form)

@users.route("/admin_dashboard")
@login_required
def admin_dashboard():
    if current_user.id == 1:
        return render_template('admin_dashboard.html', title='Admin Dashboard')
    else:
        return render_template('errors/403.html', title='Error 403')

@users.route("/patient")
@login_required
def patient():
    return render_template('patient.html', title='Patient')

Smile_Plaza/main/templates/admin_nav.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='nav.css') }}">
  </head>
  <body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <img style="margin-left: -100px;" src="{{ url_for('static', filename = 'images/toothlogo2.png') }}" class="logo" alt="logo">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse"  style="margin-right: -50px;" id="navbarToggle">
                <div class="navbar-nav mr-auto"  style="margin-left: 30px;">
                    <a class="nav-item nav-link" href="/admin_dashboard">Dashboard</a>
                    <a class="nav-item nav-link" href="/appointment_admin?date=" id="active--link">Schedule</a>
                    <a class="nav-item nav-link" href="/patient">Patient</a>
                    <a class="nav-item nav-link" href="/new_post">Post</a>
                    <a class="nav-item nav-link" href="/admin_announcement">Announcements</a>
                </div>
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                </div>
            </div>
          </div> 
        </nav>
      </header>
      <br>
      <main role="main" class="container" style="margin-left: auto; margin-right: auto; width: auto;">
        <div class="row mx-auto" style="width: 1100px;">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="col-md-12">
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
      </main>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script>
        const current_date = new Date();
        const formattedDate = current_date.toISOString().split('T')[0]; 
        const link = document.getElementById('active--link');
        link.href += formattedDate;
      </script>
  </body>
</html>

Smile_Plaza/main/templates/customer_nav.html
<!DOCTYPE html>
<html>
  <head>
    <title>Patient Portal</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='nav.css') }}">
  </head>
  <body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <img style="margin-left: -100px;" src="{{ url_for('static', filename = 'images/toothlogo2.png') }}" class="logo" alt="logo">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" style="margin-right: -50px;" id="navbarToggle">
                <div class="navbar-nav mr-auto"  style="margin-left: 30px;">
                    <a class="nav-item nav-link" href="/customer_announcement">Announcements</a>
                    <a class="nav-item nav-link" href="/appointment" >My Appointments</a> 
                    <a class="nav-item nav-link" href="/history" >History</a>
                </div>
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                </div>
            </div>
          </div>
        </nav>
    </header>
    <br>
    <main role="main" class="container" style="margin-left: auto; margin-right: auto; width: auto;">
      <div class="row mx-auto" style="max-width: 1100px;">
          {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                  <div class="col-md-12">
                      {% for category, message in messages %}
                          <div class="alert alert-{{ category }}">
                              {{ message }}
                          </div>
                      {% endfor %}
                  </div>
              {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
      </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

Smile_Plaza/main/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet"href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a href="/home">
            <img style="margin-left: -100px;" src="{{ url_for('static', filename = 'images/toothlogo2.png') }}" class="logo" alt="logo">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" style="margin-right: -50px;" id="navbarToggle">
            <div class="navbar-nav mr-auto" style="margin-left: 30px;">
              <a class="nav-item nav-link mr-2" href="/home">Home</a>
              <a class="nav-item nav-link mr-2" href="#aboutus">About</a>
              <a class="nav-item nav-link mr-2" href="#treatments">Treatments</a>
              <a class="nav-item nav-link mr-2" href="#clinic_hours">Clinic Hours</a>
              <a class="nav-item nav-link mr-2" href="/contact">Contact Us</a>
              <a class="nav-item nav-link mr-2" href="/appointment">Appointment</a>
            </div>
            <div class="navbar-nav" style="margin-right: -100px;">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link mr-2" href="{{ url_for('users.account') }}">&emsp;&emsp;Account</a>
                <a class="nav-item nav-link mr-2" href="{{ url_for('users.logout') }}">&emsp;Logout</a>
                {% if current_user.id == 1 %}
                  {% extends "admin_nav.html" %}
                {% else %}
                  {% extends "customer_nav.html" %}
                {% endif %} 
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <br>
    <main role="main" class="container" style="margin-left: auto; margin-right: auto; width: 600px;">
      <div class="row" style="max-width: 600px;">
          {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                  <div class="col-md-12">
                      {% for category, message in messages %}
                          <div class="alert alert-{{ category }}" style="position: relative;
                            padding: 0.75rem 1.25rem;
                            margin-bottom: 1rem;
                            border: 1px solid #bee5eb;
                            background-color: #d1ecf1;
                            border-radius: 0.25rem;
                            color: #0c5460;">
                            {{ message }}
                          </div>
                      {% endfor %}
                  </div>
              {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
      </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

Smile_Plaza/main/templates/login.html
{% extends "layout.html" %}
{%block content%}
    <body style="background-color: #016892;">
        <div class="container" style="background-color:#fff; border: solid 1px; border-radius: 2px; border-color: #ccc; width:565px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
            <div class="row justify-content-center">
                <div class="col-md-12 ">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }} 
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4 pt-1">Log In</legend>
                            <div class="form-group">
                                {{ form.email.label(class="form-control-label") }}
                                {% if form.email.errors %}
                                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.email.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.email(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.password.label(class="form-control-label") }}
                                {% if form.password.errors %}
                                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.password.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.password(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-check" style="cursor: pointer;">
                                {{ form.remember(class="form-check-input") }}
                                {{ form.remember.label(class="form-check-label") }}
                            </div>
                        </fieldset>
                        {{ form.recaptcha()}}
                        <div class="invalid-feedback" style="cursor: pointer; display: block;">
                            {% for error in form.recaptcha.errors %}
                                <span style="color: red;">{{ error }}</span>
                            {% endfor %} 
                        </div>
                        <br>
                        <div class="form-group"
                            onmouseover="this.querySelector('input[type=submit]').style.backgroundColor='#2b96b9'; this.querySelector('input[type=submit]').style.boxShadow='4px 4px #056892';"
                            onmouseout="this.querySelector('input[type=submit]').style.backgroundColor='#056892'; this.querySelector('input[type=submit]').style.boxShadow='4px 4px #b9f1ee';">
                            {{ form.submit(
                                class="btn btn-outline-info",
                                style="background-color: #056892; 
                                color: #fff; 
                                padding: 8px 12px; 
                                width: 120px;
                                border:none;
                                border-radius: 5px;
                                box-shadow: 4px 4px #b9f1ee;
                                font-size: 1rem;
                                font-weight: 500;
                                letter-spacing: 1px;
                                font-weight: 600;
                                transition: all .45s ease;"
                            ) }}
                            <small class="text-muted ml-2">
                                <a href="{{ url_for('users.reset_password_request') }}">Forgot Password?</a>
                            </small>
                        </div>
                    </form>
                    <div class="border-top pt-1">
                        <small class="text-muted">
                            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://www.google.com/recaptcha/api.js" async defer></script>
        <script src="https://unpkg.com/scrollreveal"></script>
        <script>
            const sr= ScrollReveal({
            distance: '60px',
            duration: 500,
            reset: true
            })
            sr.reveal('.row',{delay:200, origin:'right'})
        </script>
    </body>
{% endblock content %}

Smile_Plaza/main/templates/post.html
{% extends "admin_nav.html" %}
{% block content %}
    {% if current_user.id == 1 %}
    <div class="post mx-auto">
        <div class="col-md-12 pt-2" style="width: 600px; border: 1px solid #ccc; width: 1100px; margin-right:-20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
            <article class="media">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                    {% if post.author == current_user %}
                    {% endif %}
                </div>
                <h2 class="article-title">{{ post.title }}</h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
            <div class="mt-auto ml-auto">
                <small>
                    <a class="ml-auto" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a> 
                    <a class="ml-auto" data-toggle="modal" data-target="#deleteModal" style="cursor: pointer;">Delete</a>
                </small>
            </div>
            </article>
        </div>
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
                </div>
            </div>
            </div>
        </div>
    </div>
    <script src="https://unpkg.com/scrollreveal"></script>
    <script>
        const sr= ScrollReveal({
        distance: '60px',
        duration: 2500
        })
        sr.reveal('.col-md-12',{delay:200, origin:'top'})
    </script>
    {% endif %}
{% endblock content %}